### ISSUE TITLE
Add `options` argument for input_selectize

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#509] opened 2023-05-24 05:32 UTC
I noticed in py-shiny `input_selectize` doesn't have the `options` argument. Would be great to have that. Thanks.

https://shiny.posit.co/r/reference/shiny/1.7.4/selectinput

**Comment by nealrichardson** [comment] 2023-05-31 18:43
What's missing here is the logic in the R `selectizeIt()` function: https://github.com/rstudio/shiny/blob/main/R/input-select.R#L124-L126

**Comment by nealrichardson** [comment] 2023-06-05 14:37
Turns out this is a duplicate of #158

**Closed by nealrichardson** 2023-06-05 14:37 UTC
Labels: enhancement
