### ISSUE TITLE
shinylive 0.0.2dev no longer creating static site

### ISSUE THREAD

**Issue by jamieRowen** [rstudio/py-shiny#316] opened 2022-08-17 18:37 UTC
Attempting to run `shiny static <app_dir> target` on one of the doc examples at the moment and getting the following (some filepaths redacted from output)

```
Traceback (most recent call last):
  File "/.venv/bin/shiny", line 8, in <module>
    sys.exit(main())
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/shiny/_main.py", line 397, in static
    _static.deploy_static(
  File "/.venv/lib/python3.8/site-packages/shiny/_static.py", line 49, in deploy_static
    spec.loader.exec_module(shinylive)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jamie/.cache/shiny/shinylive/shinylive-0.0.2dev/scripts/shinylive.py", line 344, in <module>
    def _find_import_app_contents(app_contents: List[FileContentJson]) -> set[str]:
TypeError: 'type' object is not subscriptable
```

app_dir has only an app.py module and creates a shiny.App object named app (example is exact copy of one of the docs examples)

**Comment by wch** [comment] 2022-08-17 19:02
Ah, I think the problem is that I used `set[str]` instead of `Set[str]`. The former is valid only on Python 3.9+.

Can you try editing the shinylive.py file and change that to `Set[str]`?

**Comment by wch** [comment] 2022-08-17 19:11
Should be fixed by https://github.com/rstudio/py-shinylive/commit/b77f9173f6fca76ea6f321a57790891f62de71b0.

It will take about 5-10 minutes to redeploy, then you can run:

```
shiny static-assets remove
shiny static app_dir target
```

Please reopen if you still have problems.

**Closed by wch** 2022-08-17 19:11 UTC

**Comment by jamieRowen** [comment] 2022-08-17 19:18
Wow that was response was far faster than anticipated. Updating my copy of shiny live did fix the issue so should be good thanks
